### ISSUE TITLE
incorrect schema

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#10]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_search_3.md?plain=1#L62

the taggroup and tag schema needs to be fixed, it is tags[*].list[*].value/descriptor

**Comment by Vishwajith-mr** [comment]
Issue Addressed
