### ISSUE TITLE
Can we avoid multiple forms

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#11]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_search_1.md?plain=1#L152-L156

Do we need the forms to be split into 3? can it be only 1 form, regarding the 3rd form I am not sure of the purpose and also is it for all the lenders or only to the lender whose offer is selected

**Comment by samar-bizongo** [comment]
@92shreyansh we can merge the first 2 form but as document needs to be submitted as stream that will be POST call. Payload size can be larger than 10MB. to keep it minimum, we broke it down in first 2 form.

All these documents are required for loan underwriting so it needs to be sent to all lender. upon reviewing these document lender might offer the loan. and to accept the offer, 3rd form is required.

**Comment by Vishwajith-mr** [comment]
Issue Addressed
