### ISSUE TITLE
created and updated time

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#12]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_search_3.md?plain=1#L228-L229

Are these prrsent in the schema, As of now created and updated timestamps are utilized post order creation only not before that

**Comment by Vishwajith-mr** [comment]
Issue Addressed
