### ISSUE TITLE
Complete offer details required

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#13]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_select_1.md?plain=1#L40-L44

Items in all the on_* calls should have entire details and not just the id

**Comment by 92shreyansh** [comment]
@Vishwajith-mr @samar-bizongo

**Comment by Vishwajith-mr** [comment]
@92shreyansh We thought these additional details might be redundant in subsequent calls, as this information is already passed in first on_search call, keeping the specification light weight.
Any specific thoughts around this?

**Comment by Vishwajith-mr** [comment]
Issue Addressed
