### ISSUE TITLE
Can we remove Principal and Interest Amount from quote break up

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#19]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/6dd563611ad829c033b108b898069bd4366307d4/working_capital_loan/on_select_1.md?plain=1#L242C10-L255C13

**Comment by samar-bizongo** [comment]
yes, @92shreyansh 

these will be removed as we discussed yesterday. we are yet to accommodate changes that we discussed yesterday.

These were kept as per last to last discussion where we decided to keep these as it will part of term loan.

**Comment by Vishwajith-mr** [comment]
Issue Addressed
