### ISSUE TITLE
Should this not be a application/html with redirection?

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#21]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/6dd563611ad829c033b108b898069bd4366307d4/working_capital_loan/form_business_kyc.md?plain=1#L2C1-L3C1

**Comment by samar-bizongo** [comment]
These are file upload by borrower. 

Buyer App can collect files from borrower & will be able to fill form in the backend na ?

@Vishwajith-mr do we wanna add something ?

**Comment by Vishwajith-mr** [comment]
Issue Addressed
