### ISSUE TITLE
This should match the form ID of the previous call, This will be provided by seller NP

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#22]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/6dd563611ad829c033b108b898069bd4366307d4/working_capital_loan/init_2.md?plain=1#L88C1-L89C1

**Comment by samar-bizongo** [comment]
yes!

**Comment by Vishwajith-mr** [comment]
Issue Addressed
