### ISSUE TITLE
Use standard name and id in html form

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#7]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/form_gst_bank_statement.md?plain=1#L19

Let make sure we have the name and id attribute of a given form be identical/same for a given field. and lets use snake_case for the key creation

**Comment by Vishwajith-mr** [comment]
Issue Addressed
