### ISSUE TITLE
Item.descriptor.code to fix

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#8]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_search_1.md?plain=1#L75

Item code should be LOAN as we already have a category to clasify the product/service explicite item code for each use case is something that we should avoid

**Comment by Vishwajith-mr** [comment]
Issue Addressed
