### ISSUE TITLE
Are Tags mandatory

### ISSUE THREAD

**Issue by 92shreyansh** [Bizongo/ondc-b2b-loan-specification#9]
https://github.com/Bizongo/ondc-b2b-loan-specification/blob/9de1b51f8f1b96eb0ce39aaf1838fcf2b2bade51/api/on_search_1.md?plain=1#L84C50-L84C62

are we looking at making these general info tags manadatory? only recomendation is if these are present in one on_search let it be also present at other on_search's

Same hold for provider level tags for CONTACT_INFO and LSP_INFO

**Comment by Vishwajith-mr** [comment]
Issue Addressed
